### ISSUE TITLE
Cannot use commands.Commands error in rivi.go

### ISSUE THREAD

**Issue by rajendraarora16** [bivas/rivi#51]
I am trying to build this project from source code, I am getting below error in `rivi.go`:

`Cannot use commands.Commands (type map[string]cli.CommandFactory) as type map[string]CommandFactory...`

Please find the screenshot below:

![SCREENSHOT][1]

  [1]: https://i.stack.imgur.com/TE5tL.png

**Comment by bivas** [comment]
Which branch and sha? (development and master are all green)
Which Go version are you using? (tested with Go 1.8+)
Did you disable vendoring by any chance?

Source is being constantly built by Travis so it compiles without issues.
